tasks of the 2nd module
js-tasks-ru/jsbasic-20211108_alekseeffkv pull request #2
Opened 2021-11-12 10:16 UTC by alekseeffkv

Здравствуйте, Влад.
Я в первой задаче добавил проверку на целое и неотрицательное число. Нормальный вариант или можно проще сделать?

2021-11-12 10:17 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-11-12 10:48 UTC, SinimaWath requested changes

2021-11-12 10:48 UTC, SinimaWath commented on 1-module/1-task/index.js
> +    return 'n должно быть целое неотрицательное число';
Хорошо, что добавил еще проверку, хоть по заданию и не требовалось.

Но не стоит возвращать какую-то строку в качестве ошибки. Есть два варианта:
- Кинуть ошибку (будем проходить в конце курса)
- Вернуть, какое либо дефолтное значение. В случае факториала - это 1

2021-11-12 10:48 UTC, SinimaWath commented on 1-module/3-task/index.js
> +  return str == '' ? '':
А если str будет null? ТОгда ты попадешь во второе условие.

Обычно лучше все отсекать приведением типов:
`!str ? '' : ...`

!str - сразу в себя включить '', null и undefined

2021-11-12 11:51 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-11-12 12:01 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2021-11-14 13:35 UTC, SinimaWath approved these changes
Все ок

2021-11-14 13:36 UTC, merged