tasks of the 2nd module
js-tasks-ru/jsbasic-20211108_alekseeffkv pull request #3
Opened 2021-11-16 08:20 UTC by alekseeffkv

Здравствуй, Влад.
Задачи на проверку.

2021-11-16 08:21 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-11-16 10:29 UTC, SinimaWath requested changes

2021-11-16 10:29 UTC, SinimaWath commented on 2-module/2-task/index.js
> +    if (obj[key] !== null) return false;
А почему проверка на null? Если в обьекте будет свойство:
```
{
  a: null
}
```

То этот обьект уже не пустой

2021-11-16 10:46 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-11-16 10:55 UTC, alekseeffkv commented on 2-module/2-task/index.js
> +    if (obj[key] !== null) return false;
Тогда такой вариант:
```
function isEmpty(obj) {
    for (let key in obj) {
        if (key !== undefined) return false;
   }
return true;
}
```

2021-11-18 12:31 UTC, SinimaWath approved these changes
Все ок !

2021-11-18 12:31 UTC, merged