tasks of the 3rd module
js-tasks-ru/jsbasic-20211108_alekseeffkv pull request #4
Opened 2021-11-20 12:19 UTC by alekseeffkv

Влад, в 5 задаче для поиска min&max использовал цикл for.
Есть ли готовые методы массива для этого?
В интернете встретил варианты, но не особо их понял

2021-11-20 12:20 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-11-22 09:28 UTC, SinimaWath requested changes

2021-11-22 09:28 UTC, SinimaWath commented on 3-module/3-task/index.js
> +  }
Как-то слишком сложно.


Давай попоробуем избавиться от проверки arrFromStr[0] == ''.

Это ты можешь проверить, сразу в map, и не разделять на 2 ветки

2021-11-22 09:28 UTC, SinimaWath commented on 3-module/5-task/index.js
> +  }
Нормально :)

2021-11-24 06:27 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-11-25 06:13 UTC, SinimaWath approved these changes

2021-11-25 06:13 UTC, merged