tasks of the 8th module
js-tasks-ru/jsbasic-20211108_alekseeffkv pull request #9
Opened 2021-12-14 12:18 UTC by alekseeffkv

2021-12-14 12:19 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-12-15 10:29 UTC, SinimaWath requested changes

2021-12-15 10:29 UTC, SinimaWath commented on 8-module/2-task/index.js
> +            return productCard.elem.outerHTML;
Так ты потенциально можешь ломать обработку событий, на елементы elem. Потому что по сути, копируешь и вставляешь в DOM новую верстку

В этом случае, надо вставлять продукты, через append

2021-12-15 10:29 UTC, SinimaWath commented on 8-module/2-task/index.js
> +    }
Это можно упростить до:
`this.filters = {...this.filters, ...newFilter}`

Или через Object.assign

2021-12-15 10:29 UTC, SinimaWath commented on 8-module/2-task/index.js
> +    document.querySelector('.products-grid__inner').innerHTML = this.#createCards(filteredCards);
На странице потенциально может быть елемент с таким же классом. Поэтому безопасней, выбирать их относительно контейнера:

`elem.querySelector`

2021-12-15 10:29 UTC, SinimaWath commented on 8-module/3-task/index.js
> +    if (product === null || product === undefined) return;
можно упростить до:

`if (!product) return`

2021-12-15 10:29 UTC, SinimaWath commented on 8-module/3-task/index.js
> +    this.cartItems.map(item => totalCount += item.count);
Тут можно попробовать reduce, я его не показывал, на лекции, но он как раз для этих целей

2021-12-15 10:29 UTC, SinimaWath commented on 8-module/3-task/index.js
> +    this.cartItems.map(item => totalPrice += item.count * item.product.price);
Тут можно попробовать reduce, я его не показывал, на лекции, но он как раз для этих целей

2021-12-15 10:29 UTC, SinimaWath commented on 8-module/4-task/index.js
> +    document.querySelector('.modal__body').firstElementChild.addEventListener('click', event => {
а зачем тебе тут querySelector, если выше есть переменная `modalBody`, которая содержит тот же елемент

2021-12-15 13:08 UTC, alekseeffkv commented on 8-module/4-task/index.js
> +    document.querySelector('.modal__body').firstElementChild.addEventListener('click', event => {
Потому что после вызова метода
```
  setBody(modalBody) {
    this.elem.querySelector('.modal__body').innerHTML = modalBody.outerHTML;
  }
```
переменная `modalBody` уже не ссылается на `div`, на который я вешаю обработчик

2021-12-15 13:12 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-12-15 13:29 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2021-12-16 07:50 UTC, SinimaWath approved these changes

2021-12-16 07:50 UTC, merged